language: node_js
node_js:
  - 10 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - cp database.yml
script:
  - npm run build # make the bundle
before_deploy:
   - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: elemental-health # see README
  api_key:
    secure: YOUR-***ENCRYPTED***-API-KEY-HERE # see README
