production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: capstone
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DATABASE_URL'] %>
  port: <%= ENV['PORT'] %>
